version: '3.1'

services:
  postgres-db:
    image: postgres:15.5-alpine3.18
    container_name: postgres-v2
    env_file:
      - ./postgres/postgres.env
    restart: always
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    env_file:
      - path: ./.env
        required: true
    restart: always
    ports:
      - 8080:8080
    labels:
      'app': ${APPLICATION_NAME}
    depends_on:
      - postgres-db
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=PostgreSQL

  web-application:
    build: .
    command: /bin/sh -c "cd ./partition_registry/control && uvicorn mainflow:app --host 0.0.0.0 --port 5498"
    ports:
      - 5498:5498
    depends_on:
      - postgres-db
      - adminer
    environment:
      - POSTGRES_APPLICATION_HOST=postgres-db
      - POSTGRES_APPLICATION_USER=postgres
      - POSTGRES_APPLICATION_PASSWORD=changeme
      - POSTGRES_APPLICATION_DATABASE_NAME=partition_registry
