from partition_registry.actions.register_source import register_source
from partition_registry.actions.register_provider import register_provider
from partition_registry.actions.register_partition import register_partition
from partition_registry.actions.lock_partition import lock_partition
# from partition_registry.actions.lock_partition import lock_partition
# from partition_registry.actions.unlock_partition import unlock_partition
# from partition_registry.actions.is_partition_ready import is_partition_ready
